// hubly-document-build — one job, its own isolate.
//
// WHY THIS FUNCTION EXISTS
//
// Page generation is a single ~100-150s model call. It used to run inside
// hubly-conversation via EdgeRuntime.waitUntil: dispatched, not awaited, riding
// on the REQUEST isolate. waitUntil asks the runtime to keep that isolate alive
// past the response; it does not guarantee it. The runtime is free to recycle a
// request isolate the moment it has responded, which is precisely when it
// recycles one, and when it does the build vanishes with no error and no trace.
//
// Measured on 2026-08-18: three of eight real builds never wrote a document.
// The core function of the product, failing silently on more than a third of
// attempts, while the person watched a skeleton for ninety seconds.
//
// So the work moved here. A fresh isolate, whose only job is this build, with
// the whole function lifetime to itself instead of competing with a response
// that has already been sent.
//
// WHAT THIS DOES NOT CLAIM
//
// This is not a queue and does not pretend to be one. If THIS isolate dies
// mid-build the work is still lost. What is different is that the loss is now
// recorded: document_build_jobs holds a row written before the dispatch, so a
// job stuck in `running` past expected_by is provably dead rather than
// indistinguishable from slow — which is what lets the client say so and offer
// a retry instead of showing a skeleton forever. Real durability needs a worker
// outside the request path (pg_cron -> net.http_post, or Supabase Queues); that
// is the follow-up, and it is a database change nobody should make blind.
//
// DEPLOY THIS WHENEVER _shared CHANGES
//
// Each Edge Function bundles its OWN copy of supabase/functions/_shared. Moving
// generation here created a second deployment target for the renderer, and the
// first time the renderer changed only hubly-conversation was redeployed --
// so every page was still being GENERATED by the old code, while the
// conversation ran the new code. Nothing failed; the pages were just wrong, in
// a way that looked like the change had not worked.
//
//   npm run deploy:generation
//
// deploys both. Use it rather than deploying hubly-conversation alone.
//
// AUTHORISATION
//
// Service-role only. This function takes a draftId and draftToken and writes a
// document, so it must never be reachable from a browser: the caller has to
// already hold the service key, which means it is another one of our functions.
// verify_jwt stays on (see config.toml) and the bearer is checked below as
// well — two points, same discipline as everywhere else in this codebase.

import { runDocumentGeneration, finishDocumentBuildJob } from "../_shared/hubly_capability_registry.ts";
import { requireSecretKey } from "../_shared/supabase_admin.ts";

const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "authorization, x-client-info, apikey, content-type",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...CORS },
  });
}

// Set at module load — the gap between this and the first request is the
// isolate cold-boot the job clock is already paying for.
const MODULE_LOADED_AT = performance.now();

Deno.serve(async (req) => {
  const fnStart = performance.now();
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ ok: false, error: "method_not_allowed" }, 405);

  // BOTH KEY ERAS. A legacy service_role JWT arrives as a Bearer token; a new
  // sb_secret_ key cannot, because the platform gateway rejects a non-JWT
  // Bearer before this handler runs -- so it arrives on `apikey` instead.
  // Checking only Authorization would have silently 403'd every build the day
  // the keys changed.
  //
  // requireSecretKey throws when nothing resolves, which is right: a missing
  // key here must not degrade into "compare against empty string".
  let serviceKey: string;
  try {
    serviceKey = requireSecretKey().key;
  } catch (e) {
    console.error("hubly-document-build: no service key configured", e);
    return json({ ok: false, error: "not_configured" }, 500);
  }
  const bearer = (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim();
  const apikey = (req.headers.get("apikey") || "").trim();
  // Not a formality. Everything below writes a real page to a real business
  // from an unauthenticated-looking payload; the only thing standing between
  // that and the open internet is this comparison.
  if (bearer !== serviceKey && apikey !== serviceKey) {
    return json({ ok: false, error: "forbidden" }, 403);
  }

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return json({ ok: false, error: "bad_json" }, 400);
  }

  const draftId = String(body?.draftId || "").trim();
  const draftToken = String(body?.draftToken || "").trim();
  const brief = String(body?.brief || "").trim();
  const jobId = body?.jobId ? String(body.jobId) : null;

  if (!draftId || !draftToken || !brief) {
    await finishDocumentBuildJob(jobId, "failed", "missing_input");
    return json({ ok: false, error: "missing_input" }, 400);
  }

  // AWAITED, not backgrounded. That is the entire point of this function
  // existing: the response is not sent until the build is finished, so the
  // runtime has no reason to recycle the isolate underneath it.
  try {
    const preamble = Math.round(performance.now() - fnStart);
    const result = await runDocumentGeneration(draftId, draftToken, brief);
    const inFunction = Math.round(performance.now() - fnStart);
    // dispatchedAt is stamped by hubly-conversation immediately before the HTTP
    // call, so (arrival - dispatchedAt) is the round trip plus cold boot -- the
    // part of the job clock that happens before this function does anything.
    const dispatchedAt = Number((body as Record<string, unknown>)?.dispatchedAt) || 0;
    const handoff = dispatchedAt ? Math.round(Date.now() - dispatchedAt - inFunction) : null;
    console.log(`build-timing-fn [${draftId}] ${JSON.stringify({ preamble, inFunction, handoffAndBoot: handoff, moduleLoad: Math.round(fnStart - MODULE_LOADED_AT) })}`);
    await finishDocumentBuildJob(
      jobId,
      result.ok ? "succeeded" : "failed",
      // A short code, never the model's own output — get_document_build_status
      // surfaces this field publicly.
      result.ok ? undefined : String(result.error || "generation_failed"),
    );
    console.log(`hubly-document-build [${draftId}] ${result.ok ? "succeeded" : "FAILED"}: ${result.summary}`);
    return json({ ok: result.ok, summary: result.summary });
  } catch (e) {
    // An exception here is the case the old code could not distinguish from an
    // isolate death. Recording it is the difference between a bug we can find
    // and a 37% failure rate nobody can explain.
    console.error(`hubly-document-build [${draftId}] threw`, e);
    await finishDocumentBuildJob(jobId, "failed", "exception");
    return json({ ok: false, error: "exception" }, 500);
  }
});
