/** Node mirror of hubly_brain_certification.ts — Section 18 (esbuild). */


// supabase/functions/_shared/hubly_brain_certification.ts
var CERTIFICATION_VERSION = "1.0.0";
var CERTIFICATION_OWNER = "hubly_brain";
var MILESTONE1_BRAIN_VERSION = "1.0";
var DIMENSION_META = {
  thinking: { label: "Thinking" },
  memory: { label: "Memory" },
  reasoning: { label: "Reasoning" },
  identity: { label: "Identity" },
  decisionMaking: { label: "Decision Making" },
  capabilityDiscovery: { label: "Capability Discovery" },
  missionControl: { label: "Mission Control" },
  reliability: { label: "Reliability" },
  businessKnowledge: { label: "Business Knowledge" }
};
var lastScorecard = null;
var lastCertificate = null;
var lastScenarioCount = 0;
function clampPct(n) {
  return Math.max(0, Math.min(100, Math.round(n)));
}
function scoreDimension(id, passed, total, detail = "") {
  const score = total <= 0 ? 0 : clampPct(passed / total * 100);
  return {
    id,
    label: DIMENSION_META[id].label,
    score,
    passed: score >= 100,
    detail: detail || `${passed}/${total}`
  };
}
function buildCertificationScorecard(opts) {
  const dims = opts.dimensions;
  const values = Object.values(dims).map((d) => d.score);
  const overall = values.length ? clampPct(values.reduce((a, b) => a + b, 0) / values.length) : 0;
  const certified = overall >= 100 && opts.scenariosPassed === opts.scenariosTotal && opts.scenariosTotal > 0 && opts.founderBenchmarksOk && opts.validationSuitesOk && opts.documentationOk;
  return {
    version: CERTIFICATION_VERSION,
    overall,
    dimensions: dims,
    scenariosPassed: opts.scenariosPassed,
    scenariosTotal: opts.scenariosTotal,
    founderBenchmarksOk: opts.founderBenchmarksOk,
    validationSuitesOk: opts.validationSuitesOk,
    documentationOk: opts.documentationOk,
    certified,
    checkedAt: opts.checkedAt || (/* @__PURE__ */ new Date()).toISOString()
  };
}
function buildMilestone1Certificate(opts) {
  const certified = opts.scorecard.certified;
  return {
    title: "Milestone 1 Completion Certificate",
    product: "Hubly Brain",
    version: MILESTONE1_BRAIN_VERSION,
    status: certified ? "Certified" : "Not Certified",
    date: opts.date || opts.scorecard.checkedAt.slice(0, 10),
    release: "Milestone 1",
    pr: opts.pr || "https://github.com/HubblyAdrian/Hubly/pull/196",
    validationSuite: "npm run milestone1 \xB7 npm run check:section16 \xB7 npm run check:section18",
    founderApproval: opts.founderApproval || (certified ? "Pending Founder Sign-Off" : "Not ready"),
    nextMilestone: "1.5 \u2014 Builder Engine",
    certificationScore: opts.scorecard.overall,
    scorecardPath: "docs/HUBLY_BRAIN_SECTION18_PROOF.json",
    certificatePath: "docs/releases/MILESTONE1_CERTIFIED.md"
  };
}
function recordBrainCertification(opts) {
  lastScorecard = opts.scorecard;
  lastCertificate = opts.certificate;
  lastScenarioCount = opts.scenarioCount;
}
function getBrainCertificationSnapshot() {
  return {
    version: CERTIFICATION_VERSION,
    owner: CERTIFICATION_OWNER,
    scorecard: lastScorecard,
    certificate: lastCertificate,
    scenarioCount: lastScenarioCount,
    lastCheckedAt: lastScorecard?.checkedAt ?? null
  };
}
function clearCertificationForTests() {
  lastScorecard = null;
  lastCertificate = null;
  lastScenarioCount = 0;
}
function renderMilestone1CertificateMarkdown(cert, scorecard) {
  const dimLines = Object.values(scorecard.dimensions).map((d) => `| ${d.label} | ${d.score}% |`).join("\n");
  return `# Milestone 1 Completion Certificate

## Hubly Brain

| Field | Value |
|-------|-------|
| **Product** | ${cert.product} |
| **Version** | ${cert.version} |
| **Status** | **${cert.status}** |
| **Date** | ${cert.date} |
| **Release** | ${cert.release} |
| **PR** | ${cert.pr} |
| **Validation Suite** | ${cert.validationSuite} |
| **Founder Approval** | ${cert.founderApproval} |
| **Next Milestone** | ${cert.nextMilestone} |
| **Certification Score** | ${cert.certificationScore}% |

## Hubly Brain Certification Scorecard

| Dimension | Score |
|-----------|------:|
| **Overall** | **${scorecard.overall}%** |
${dimLines}

## Scenarios

${scorecard.scenariosPassed}/${scorecard.scenariosTotal} founder acceptance scenarios passed.

- Founder Benchmark Suite: ${scorecard.founderBenchmarksOk ? "Pass" : "Fail"}
- Validation suites: ${scorecard.validationSuitesOk ? "Pass" : "Fail"}
- Documentation: ${scorecard.documentationOk ? "Pass" : "Fail"}

---

*This certificate is generated by Section 18 \u2014 Founder Acceptance & Brain Certification.*  
*Machine proof: \`${cert.scorecardPath}\`*
`;
}
var HublyCertification = {
  version: CERTIFICATION_VERSION,
  owner: CERTIFICATION_OWNER,
  scoreDimension,
  buildScorecard: buildCertificationScorecard,
  buildCertificate: buildMilestone1Certificate,
  record: recordBrainCertification,
  snapshot: getBrainCertificationSnapshot,
  renderMarkdown: renderMilestone1CertificateMarkdown,
  clearForTests: clearCertificationForTests
};
export {
  CERTIFICATION_OWNER,
  CERTIFICATION_VERSION,
  HublyCertification,
  MILESTONE1_BRAIN_VERSION,
  buildCertificationScorecard,
  buildMilestone1Certificate,
  clearCertificationForTests,
  getBrainCertificationSnapshot,
  recordBrainCertification,
  renderMilestone1CertificateMarkdown,
  scoreDimension
};
